FROM maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /build

COPY ./pom.xml ./

RUN mvn dependency:go-offline

COPY ./src ./src

RUN mvn clean install -DskipTests

FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app
COPY --from=builder /build/target/FeedSync-0.0.1-SNAPSHOT.jar app.jar

# COPY .env ./

RUN mkdir -p /app/logs

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]